Algoritmo "semnome"
// 
//  
// Descrição   : O Restaurante cobra R$12,00 por cada quilo de refeição.
//Escreva um algoritmo que leia o preço do prato montado pelo cliente
//(em quilos) e imprima o valor a pagar. Assuma que a balança já desconte
//o preço do prato
// Autor(a)    : Jairo Jannini Junior
// Data atual  : 18/4/2023

// Seção de Declarações das variáveis 
var

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

Fimalgoritmo