Algoritmo "Exercício 50 6-m"
// 
//  
// Descrição   : Soma dos quadrados
// Autor(a)    : Jairo Jannini Junior
// Data atual  : 9/6/2023
Var
// Seção de Declarações das variáveis 
   A , B , C : inteiro
   s :real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Digite o primeiro valor: ")
   leia(A)
   escreval("Digite o segundo valor: ")
   leia(B)
   escreval("Digite o terceiro valor: ")
   leia(C)
   s <- A^2 + B^2 + C^2
   escreval(s)

Fimalgoritmo