Algoritmo "Exercício 44 A"
// 
//  
// Descrição   : Conversão temperatura
// Autor(a)    : Jairo Jannini Junior
// Data atual  : 10/5/2023
Var
// Seção de Declarações das variáveis 
   C , F : real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Qual a temperatura em Fahrenheit?")
   leia(F)
   C <- (F-32)*(5/9)
   escreval(F," Graus Fahrenheit equivalem a ",C,"º Celcius.")

Fimalgoritmo