Algoritmo "Exercício 50 6-H"
// 
//  
// Descrição   : Volume caixa
// Autor(a)    : Jairo Jannini Junior
// Data atual  : 30/5/2023
Var
// Seção de Declarações das variáveis 
   alt , larg , comp : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Qual a altura")
   leia(alt)
   escreval("Qual a largura")
   leia(larg)
   escreval("Qual o comprimento")
   leia(comp)
   escreval("O volume é",alt * larg * comp)


Fimalgoritmo