Algoritmo "Exercícios 24"
// 
//  
// Descrição   : Calcular litros de água e suco
// Autor(a)    : Jairo Jannini Junior
// Data atual  : 6/5/2023
Var
// Seção de Declarações das variáveis 
   agua , suco , ref : real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Quantos litros de refresco: ")
   leia(ref)
   agua <- ref*0.8
   suco <- ref*0.2
   escreva("São necessários ",agua," litros de água e ",suco," litros de suco.")

Fimalgoritmo