Algoritmo "Exercício 37"
// 
//  
// Descrição   : Tabuada
// Autor(a)    : Jairo Jannini Junior
// Data atual  : 10/5/2023
Var
// Seção de Declarações das variáveis 
   num , ct , m: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Digite um número inteiro")
   leia(num)
   ct <- 0
   enquanto ct <= 10 faca
            m <- ct * num
            escreval(num," X ",ct," = ",m)
            ct <- ct + 1
   fimenquanto
   


Fimalgoritmo