Algoritmo "Exercício 28"
// 
//  
// Descrição   : Media notas
// Autor(a)    : Jairo Jannini Junior
// Data atual  : 6/5/2023
Var
// Seção de Declarações das variáveis 
   n1, n2 , m : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Qual a primeira nota: ")
   leia(n1)
   escreval("Qual a segunda nota: ")
   leia(n2)
   m <- (n1*2 + n2*3)/5
   escreval("A média é ",m)
   


Fimalgoritmo