Algoritmo "Exercício 29"
// 
//  
// Descrição   : Novo preço de um produto
// Autor(a)    : Jairo Jannini Junior
// Data atual  : 6/5/2023
Var
// Seção de Declarações das variáveis 
   preco , novo : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Qual o preço do produto: ")
   leia(preco)
   novo <- preco * 0.9
   escreval("o novo preco é R$",novo)

Fimalgoritmo