Algoritmo "Exercício 36"
// 
//  
// Descrição   : Calcular salários mínimos
// Autor(a)    : Jairo Jannini Junior
// Data atual  : 10/5/2023
Var
// Seção de Declarações das variáveis 
   sal , salmin : real
   

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Qual o valor do seu salário? ")
   leia(sal)
   salmin <- sal / 1302
   escreval("Em 2023 seu salário de R$",sal,"Equivale a ",salmin," Salários mínimos")

Fimalgoritmo