Algoritmo "Exercício 17"
// 
//  
// Descrição   : Conversão Celsius Fahrenheit
// Autor(a)    : Jairo Jannini Junior
// Data atual  : 6/5/2023
Var
// Seção de Declarações das variáveis 
   C , F : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Digite a temperatura em Celcius.")
   leia(C)
   F <- C * 1.8 + 32
   escreval(C,"º Celcius equivalem a ", F, " Graus Fahrenheit")

Fimalgoritmo