Algoritmo "Exercício 40"
// 
//  
// Descrição   : hipotenusa
// Autor(a)    : Jairo Jannini Junior
// Data atual  : 10/5/2023
Var
// Seção de Declarações das variáveis 
   c1 , c2  : inteiro
   h : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Digite o tamanho do pirmeiro cateto")
   leia(c1)
   escreval("Digite o tamanho do segundo cateto")
   leia(c2)
   h <- ((c1^2)+(c2^2))^0.5
   escreval("A hipotenusa tem o tamanho de ",h)

Fimalgoritmo