Algoritmo "Exercício 32"
// 
//  
// Descrição   : Conversão kg para g
// Autor(a)    : Jairo Jannini Junior
// Data atual  : 6/5/2023
Var
// Seção de Declarações das variáveis
   kilo , grama : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreval("Digite o peso em kg: ")
   leia(kilo)
   grama <- kilo*1000
   escreval(kilo,"kg em gramas é",grama,"g.")


Fimalgoritmo