Algoritmo "Exercício 35"
// 
//  
// Descrição   : área losango
// Autor(a)    : Jairo Jannini Junior
// Data atual  : 6/5/2023
Var
// Seção de Declarações das variáveis
   a , d1 , d2 : real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Digite o tamanho da diagonal maior: ")
   leia(d1)
   escreval("Digite o tamanho da diagonal menor : ")
   leia(d2)
   a <- d1*d2
   escreval("A área é de: ", a)


Fimalgoritmo