Algoritmo "Exercício 50 6-A"
// 
//  
// Descrição   : Converter Fahrenheit Celcius
// Autor(a)    : Jairo Jannini Junior
// Data atual  : 21/5/2023
Var
// Seção de Declarações das variáveis 
   F , C : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Digite  o valor da tempretaura em graus Celcius")
   leia(C)
   F <- (9*C + 160) / 5
   escreval(C,"º graus Celcius equivalem a ",F,"º Fahrenheit.")
Fimalgoritmo