Algoritmo "Exercício 50 6-A"
// 
//  
// Descrição   : Converter Fahrenheit Celcius
// Autor(a)    : Jairo Jannini Junior
// Data atual  : 21/5/2023
Var
// Seção de Declarações das variáveis 
   F , C : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Digite  o valor da tempretaura em Farenheit")
   leia(F)
   C <- (F*5 - 160) / 9
   escreval(F,"º Farenheit equivalem a ",C,"º Celcius.")
Fimalgoritmo